### ISSUE TITLE
Badges are broken

### ISSUE THREAD

**Issue by nickago** [nickfrostatx/gitcontrib#5]
I submitted a pull request https://github.com/nickfrostatx/gitcontrib/pull/4 to try and fix them, but this might be better left in the career software developer's hands.

**Comment by nickfrostatx** [comment]
img.shields.io looks down. Their Travis also started failing about a day ago. They're generally pretty awesome, it'll be a shame to have to move away.

The [Travis build](https://travis-ci.org/badges/shields/builds/97102831) is failing because of the dependency ``libgif-dev``, even though the commit - badges/shields@e07cc5815cb8fa98de5cf5468f247d6c403f1e1e - doesn't touch dependencies.  Looks like an environment change on Travis's end.  They [about moving legacy builds](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) within the last day, so that might be it.  However, I don't see any significant environment differences from the logs between build [817](https://travis-ci.org/badges/shields/builds/96855289) and [818](https://travis-ci.org/badges/shields/builds/97098378).  So it's probably just a separate issue, unless the same dependency problem popped up on their production server (removed from the package index or something?)

All that aside, maybe we give them until the morning to gather their shit?

**Comment by nickago** [comment]
Badges are back working so I'm going to close this issue
